cache: &global_cache
  key: ${CI_PROJECT_NAME}
  paths:
    - deps
    - _build/
    - assets/node_modules/

stages:
  - test

test:
  stage: test
  image: quay.io/vizlegalq/elixir-nodejs:1.12.3-slim
  variables:
    SECRET_KEY_BASE: "MPyVFpBIthyGt1ZsfsCgvF0z32RHe3jFulOx2lkjq0L5M9/AIqexgcVnQe5OUyeM"
    HOST: 127.0.0.1
    MIX_ENV: test
  script:
    - mix deps.get
    - mix coveralls
  cache:
    <<: *global_cache

audit:
  stage: test
  image: quay.io/vizlegalq/elixir-nodejs:1.12.3-slim
  script:
    - mix deps.get
    - mix deps.audit
  cache:
    <<: *global_cache
    policy: pull

dialyze:
  stage: test
  image: quay.io/vizlegalq/elixir-nodejs:1.12.3-slim
  script:
    - mix deps.get
    - mix dialyzer
  cache:
    <<: *global_cache
    policy: pull